apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: thanos-metrics-reader
  namespace: <NAMESPACE>             # update this
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: thanos-metrics-reader
subjects:
- kind: ServiceAccount
  name: <SERVICE_ACCOUNT>            # update this
  namespace: <NAMESPACE>             # update this